// Generates the VAPID key pair that Web Push needs and writes it to .env.local.
// Run once:  npm run vapid
const fs = require("fs");
const path = require("path");
const webpush = require("web-push");

const keys = webpush.generateVAPIDKeys();
const envPath = path.join(__dirname, "..", ".env.local");

const lines = [
  `# Web Push (VAPID) keys — generated by "npm run vapid". Keep the private key secret.`,
  `NEXT_PUBLIC_VAPID_PUBLIC_KEY=${keys.publicKey}`,
  `VAPID_PRIVATE_KEY=${keys.privateKey}`,
  `VAPID_SUBJECT=mailto:you@example.com`,
  ``,
  `# Optional: real live scores from football-data.org (free tier).`,
  `# Leave blank to run in DEMO mode (fake goals so you can see notifications work).`,
  `FOOTBALL_API_TOKEN=`,
  ``,
].join("\n");

fs.writeFileSync(envPath, lines);
console.log("Wrote VAPID keys to .env.local");
console.log("Public key:", keys.publicKey);
